from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Players_Table(Base):
    __tablename__ = "v_players3"

    PLAYER_NAME = Column(String)
    PLAYER_ID = Column(String, primary_key=True)
    TEAM_ID = Column(String)
    TEAM_ABBREVIATION = Column(String)
    SEASON = Column(String, primary_key=True)
    AGE = Column(Integer)
    PLAYER_HEIGHT_INCHES = Column(Integer)
    PLAYER_WEIGHT = Column(Integer)
    DRAFT_YEAR = Column(String)
    DRAFT_ROUND = Column(Integer)
    DRAFT_NUMBER = Column(Integer)
    GP = Column(Integer)
    MIN = Column(Integer)
    PTS = Column(Integer)
    EFG_PCT = Column(Integer)
    TS_PCT = Column(Integer)
    FGM = Column(Integer)
    FGA = Column(Integer)
    FG_PCT = Column(Integer)
    FG3M = Column(Integer)
    FG3A = Column(Integer)
    FG3_PCT = Column(Integer)
    FTM = Column(Integer)
    FTA = Column(Integer)
    FT_PCT = Column(Integer)
    OREB = Column(Integer)
    DREB = Column(Integer)
    REB = Column(Integer)
    AST = Column(Integer)
    TOV = Column(Integer)
    STL = Column(Integer)
    BLK = Column(Integer)
    PF = Column(Integer)
    PFD = Column(Integer)
    PLUS_MINUS = Column(Integer)
    OFF_RATING = Column(Integer)
    DEF_RATING = Column(Integer)
    NET_RATING = Column(Integer)
    AST_PCT = Column(Integer)
    AST_TO = Column(Integer)
    AST_RATIO = Column(Integer)
    OREB_PCT = Column(Integer)
    DREB_PCT = Column(Integer)
    REB_PCT = Column(Integer)
    USG_PCT = Column(Integer)
    PACE = Column(Integer)
    PIE = Column(Integer)
    POSS = Column(Integer)
    DEFLECTIONS = Column(Integer)
    CHARGES_DRAWN = Column(Integer)
    SCREEN_ASSISTS = Column(Integer)
    PTS_OFF_TOV = Column(Integer)
    PTS_2ND_CHANCE = Column(Integer)
    PTS_FB = Column(Integer)
    PTS_PAINT = Column(Integer)
    DEF_FG3M = Column(Integer)
    DEF_FG3A = Column(Integer)
    DEF_FG3_PCT = Column(Integer)
    DEF_FG2M = Column(Integer)
    DEF_FG2A = Column(Integer)
    DEF_FG2_PCT = Column(Integer)
    TEAM_NAME = Column(String)
